### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by iveoles** [tobeychris/hipchat-room-message-APIv2#1]
Hi

When I try to send a message without notifying the room I still get popups in the Windows client. An example call is below

./hipchat.pl -room "Cluster" -token "TOK" -message "Server Online" -type text -api v2 -notify false -colour green

Am I using the disable function correctly?

**Comment by tobeychris** [comment]
Yep, sadly this has been broken in the windows client for a long time and they have not fixed it. Any message from the API will trigger a notification in the windows client. It should work on the web and other clients though.

**Comment by iveoles** [comment]
When I'm using the PHP library it seems to work correctly, in that notifications are not presented. 

Is it just the pearl interface which causes this? I'm about to test with a python client to confirm.

**Comment by tobeychris** [comment]
Were you able to see anything about this?

**Comment by tobeychris** [comment]
Version 4.x of the Windows clients work correctly for me.
